package com.employee.constants;

public enum EmployeeStates {
    ADDED, IN_CHECK, APPROVED, ACTIVE,JOIN,FORK,
    // IN_CHECK SubStates
    SECURITY_CHECK_STARTED, SECURITY_CHECK_FINISHED, WORK_PERMIT_CHECK_STARTED, WORK_PERMIT_CHECK_PENDING_VERIFICATION, WORK_PERMIT_CHECK_FINISHED
}
