package com.employee.constants;

public enum EmployeeEvents {
    BEGIN_CHECK, IN_CHECK_SECURITY_CHECK, IN_CHECK_WORK_PERMIT_CHECK, FINISH_SECURITY_CHECK, COMPLETE_INITIAL_WORK_PERMIT_CHECK, FINISH_WORK_PERMIT_CHECK, ACTIVATE
}
